name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [Debug, Release]
    name: ci (${{ matrix.build_type }})
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install dependencies
        run: |
          make setup

      - name: Configure
        run: |
          make configure CMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        run: |
          make build

      - name: Test
        run: |
          make test

      - name: Upload examples
        if: matrix.build_type == 'Release'
        uses: actions/upload-artifact@v4
        with:
          name: summa-examples
          path: |
            build/examples/examples.*
