name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          make setup

      - name: Configure
        run: |
          make configure

      - name: Build
        run: |
          make build

      - name: Test
        run: |
          make test

      - name: Upload examples
        uses: actions/upload-artifact@v4
        with:
          name: summa-examples
          path: |
            build/examples/examples.*
